"""Self-contained HTML reports — every metric drawn with its error bar.

One file, no external assets, openable anywhere (including air-gapped
machines) and safe to attach to a PR or email. The visual language is the
holdout brand: Vault black canvas, Starlight Gold accents, Snow text, and
confidence intervals rendered as literal error bars.
"""

import html as _html
from collections.abc import Iterable, Sequence

import holdout
from holdout.core.run import Run
from holdout.regression.compare import MetricComparison, RunComparison
from holdout.stats.estimate import Estimate

VAULT = "#0E0E10"
GOLD = "#C9A876"
SNOW = "#F5F5F2"
MUTED = "#8B8B93"
CARD = "#161619"
BORDER = "#26262B"
RED = "#E5484D"
GREEN = "#46A758"

_CSS = f"""
:root {{ color-scheme: dark; }}
* {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{
  background: {VAULT}; color: {SNOW};
  font-family: -apple-system, "SF Pro Display", "SF Pro Text", "SF Pro",
    system-ui, "Segoe UI", Roboto, sans-serif;
  -webkit-font-smoothing: antialiased;
  padding: 48px 24px; max-width: 860px; margin: 0 auto;
}}
.mono {{ font-family: "SF Mono", ui-monospace, SFMono-Regular, Menlo, monospace; }}
h1 {{ font-size: 22px; font-weight: 600; letter-spacing: -0.02em; }}
.sub {{ color: {MUTED}; font-size: 13px; margin-top: 6px; }}
.card {{
  background: {CARD}; border: 1px solid {BORDER}; border-radius: 14px;
  padding: 20px 24px; margin-top: 20px;
}}
.metric {{ display: grid; grid-template-columns: 200px 1fr; gap: 6px 18px;
  align-items: center; padding: 14px 0; border-bottom: 1px solid {BORDER}; }}
.metric:last-child {{ border-bottom: none; }}
.metric .name {{ font-size: 14px; font-weight: 500; }}
.metric .est {{ color: {MUTED}; font-size: 12px; }}
.verdict {{ display: inline-block; border-radius: 999px; padding: 4px 14px;
  font-size: 12px; font-weight: 600; letter-spacing: 0.04em; }}
.v-regressed {{ background: {RED}22; color: {RED}; border: 1px solid {RED}55; }}
.v-improved {{ background: {GREEN}22; color: {GREEN}; border: 1px solid {GREEN}55; }}
.v-neutral {{ background: {MUTED}22; color: {MUTED}; border: 1px solid {MUTED}55; }}
.v-gold {{ background: {GOLD}22; color: {GOLD}; border: 1px solid {GOLD}55; }}
.warn {{ color: {GOLD}; font-size: 13px; margin-top: 8px; }}
.foot {{ color: {MUTED}; font-size: 12px; margin-top: 28px; text-align: center; }}
table.kv {{ font-size: 13px; border-collapse: collapse; }}
table.kv td {{ padding: 2px 14px 2px 0; color: {MUTED}; }}
table.kv td:last-child {{ color: {SNOW}; }}
"""


def _esc(text: str) -> str:
    return _html.escape(text, quote=True)


def _domain(estimates: Iterable[Estimate]) -> tuple[float, float]:
    """Compute a padded axis domain covering every interval (10% margins)."""
    lows, highs = [], []
    for e in estimates:
        lows.append(e.ci_low)
        highs.append(e.ci_high)
    lo, hi = min(lows), max(highs)
    pad = (hi - lo) * 0.1 or max(abs(hi), 1.0) * 0.05
    return lo - pad, hi + pad


def _error_bar(
    est: Estimate, domain: tuple[float, float], *, color: str = GOLD, width: int = 420
) -> str:
    """Render one estimate as an SVG error bar within ``domain``."""
    d0, d1 = domain
    span = (d1 - d0) or 1.0

    def x(v: float) -> float:
        return round(8 + (v - d0) / span * (width - 16), 1)

    h, mid = 22, 11
    return (
        f'<svg width="{width}" height="{h}" viewBox="0 0 {width} {h}" '
        f'role="img" aria-label="{est.value:.3f}, CI {est.ci_low:.3f} to {est.ci_high:.3f}">'
        f'<line x1="8" x2="{width - 8}" y1="{mid}" y2="{mid}" stroke="{BORDER}" stroke-width="1"/>'
        f'<line x1="{x(est.ci_low)}" x2="{x(est.ci_high)}" y1="{mid}" y2="{mid}" '
        f'stroke="{color}" stroke-width="2"/>'
        f'<line x1="{x(est.ci_low)}" x2="{x(est.ci_low)}" y1="{mid - 5}" y2="{mid + 5}" '
        f'stroke="{color}" stroke-width="2"/>'
        f'<line x1="{x(est.ci_high)}" x2="{x(est.ci_high)}" y1="{mid - 5}" y2="{mid + 5}" '
        f'stroke="{color}" stroke-width="2"/>'
        f'<circle cx="{x(est.value)}" cy="{mid}" r="3.5" fill="{color}"/>'
        "</svg>"
    )


def _page(title: str, body: str) -> str:
    return (
        "<!doctype html>\n"
        '<html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        f"<title>{_esc(title)}</title><style>{_CSS}</style></head>\n"
        f"<body>{body}"
        f'<p class="foot">generated by holdout v{holdout.__version__} — '
        "every metric carries its uncertainty</p></body></html>\n"
    )


def render_run_report(run: Run, *, level: float = 0.95) -> str:
    """Render a single run as a self-contained HTML page.

    Parameters
    ----------
    run
        The run to render.
    level
        Confidence level for the intervals.
    """
    metrics = run.metrics(level=level)
    rows = []
    for name, est in metrics.items():
        dom = _domain([est])
        rows.append(
            f'<div class="metric"><div><div class="name">{_esc(name)}</div>'
            f'<div class="est mono">{_esc(str(est))}</div></div>'
            f"<div>{_error_bar(est, dom)}</div></div>"
        )
    errors = (
        f'<p class="warn">{run.n_errors} case(s) failed and are excluded from aggregates</p>'
        if run.n_errors
        else ""
    )
    body = (
        f"<h1>{_esc(run.eval_name)}</h1>"
        f'<p class="sub mono">run {_esc(run.short_run_id)} · target {_esc(run.target_name)} · '
        f"n={len(run.results)} · seed={run.seed} · {_esc(run.created_at)}</p>"
        f'<div class="card">{"".join(rows)}</div>{errors}'
    )
    return _page(f"holdout — {run.eval_name}", body)


_VERDICT_CLASS = {
    "regressed": "v-regressed",
    "improved": "v-improved",
    "no_significant_change": "v-neutral",
    "insufficient_data": "v-gold",
}
_VERDICT_TEXT = {
    "regressed": "REGRESSED",
    "improved": "IMPROVED",
    "no_significant_change": "NO SIGNIFICANT CHANGE",
    "insufficient_data": "INSUFFICIENT DATA",
}


def _comparison_row(c: MetricComparison) -> str:
    badge = f'<span class="verdict {_VERDICT_CLASS[c.verdict]}">{_VERDICT_TEXT[c.verdict]}</span>'
    if c.result is None or c.baseline is None or c.candidate is None:
        return (
            f'<div class="metric"><div><div class="name">{_esc(c.metric)}</div>'
            f'<div class="est">{_esc(c.note or "untestable")}</div></div><div>{badge}</div></div>'
        )
    dom = _domain([c.baseline, c.candidate])
    p = c.p_adjusted if c.p_adjusted is not None else c.result.p_value
    detail = f"Δ={c.result.effect:+.3f} · p={p:.4g} · {_esc(c.result.test)} · n={c.n_pairs} pairs"
    return (
        f'<div class="metric"><div><div class="name">{_esc(c.metric)} {badge}</div>'
        f'<div class="est mono">{detail}</div>'
        f'<div class="est mono">baseline  {_esc(str(c.baseline))}</div>'
        f'<div class="est mono">candidate {_esc(str(c.candidate))}</div></div>'
        f"<div>{_error_bar(c.baseline, dom, color=MUTED)}{_error_bar(c.candidate, dom)}</div>"
        "</div>"
    )


def render_comparison_report(cmp: RunComparison) -> str:
    """Render a two-run comparison as a self-contained HTML page.

    Parameters
    ----------
    cmp
        The comparison produced by :func:`holdout.regression.compare`.
    """
    rows = [_comparison_row(c) for c in cmp.comparisons]
    warnings: Sequence[str] = cmp.warnings
    warn_html = "".join(f'<p class="warn">⚠ {_esc(w)}</p>' for w in warnings)
    badge = (
        f'<span class="verdict {_VERDICT_CLASS[cmp.verdict]}">{_VERDICT_TEXT[cmp.verdict]}</span>'
    )
    baseline_label = f"{_esc(cmp.baseline_target)} ({_esc(cmp.baseline_run_id[:12])})"
    candidate_label = f"{_esc(cmp.candidate_target)} ({_esc(cmp.candidate_run_id[:12])})"
    body = (
        f"<h1>{_esc(cmp.eval_name)} {badge}</h1>"
        f'<p class="sub mono">baseline {baseline_label} vs candidate {candidate_label} · '
        f"alpha={cmp.alpha:g} · correction={_esc(cmp.correction)}</p>"
        f'<div class="card">{"".join(rows)}</div>{warn_html}'
    )
    return _page(f"holdout — {cmp.eval_name} comparison", body)
